---
title: "01 Mass Spectrometry Data Analysis"
author: "Joanna Krupka"
date: "October 15, 2019"
output: 
  html_document:
    theme: cosmo
    code_folding: show
---

### Introduction  

Here we perform a differential abundance analysis of mass-spectrometry datasets in order to validate the Ribo-Seq findings  

### Materials and methods  

```{r eval = T, echo = T, message = F, warning = F, cache = F, error = F}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(biomaRt)
library(corrplot)
library(DEP)
library(pheatmap)
library(matrixStats)
library(SummarizedExperiment)
library(clusterProfiler)
library(org.Hs.eg.db)
library(ReactomePA)
library(msigdbr)

source("../utilis.R")
#source("../solarisFunctions.R")

RiboRNA_U2932kd <- read_csv("../04_RiboSeq/results/U2932_DXsumTab.csv")
RPs <- read_csv("../utilis/signatures/HUGO_ribosomal_proteins_all.csv")

DEPtest <- function(ms_data, metadata, Experiment, Conditions, padj, lfc, normalize){
  #Match metadata and conditions
  meta <- metadata %>% filter(experiment == Experiment & condition %in% Conditions)
  
  #Check for duplicated gene names
  if(ms_data$Name %>% duplicated() %>% any()){
    data_unique <- make_unique(ms_data, "Name", "Accession", delim = ";")
    
  } else {
    data_unique <- ms_data
  }

  #Select abundance columns, create SummarizedExperiment object
  Abundance_columns <- grep("Abundances", colnames(data_unique))
  names(Abundance_columns) <- gsub("[)]: ", "...", gsub(" [(]", "..", colnames(data_unique)[Abundance_columns]))
  Abundance_columns <- Abundance_columns[match(meta$label, names(Abundance_columns))]
  colnames(data_unique)[Abundance_columns] <- names(Abundance_columns)
  Abundance_columns <- unname(Abundance_columns)
  experimental_design <- meta[,1:3] %>% na.omit()
  data_se <- make_se(data_unique, Abundance_columns, experimental_design)

  # Filter for proteins that are identified in 2 out of 3 replicates of at least one condition
  data_filt2 <- filter_missval(data_se, thr = 0)

  # Normalize the data
  if(normalize) {
    data_norm <- normalize_vsn(data_filt2)
  } else {
    data_norm <- data_filt2
  }

  
  # Impute missing data using random draws from a Gaussian distribution centered around a minimal value (for MNAR)
  data_imp <- impute(data_norm, fun = "MinProb", q = 0.01)
  
  # Test manually defined comparisons
  data_diff_manual <- test_diff(data_imp, type = "manual", 
                                test = paste0(Conditions[2], "_vs_", Conditions[1]))

  # Denote significant proteins based on user defined cutoffs
  dep <- add_rejections(data_diff_manual, alpha = padj, lfc = lfc)

  data_results <- get_results(dep)
  print(paste(paste0(Conditions[2], " vs. ", Conditions[1]), "Number of significant discoveries:"))
  print(sum(data_results[,4] < padj & abs(data_results[,7]) > lfc))
  
  #Set colnames
  data_results <- data_results[,-6]
  colnames(data_results) <- c("Name", "ID", "P_value", "FDR", "Significant", "log2FC", 
                              paste0(Conditions[1], "_centered"),  paste0(Conditions[2], "_centered"))
  
  return(list(data_results, dep, data_norm))
}

#Filter data: (IsMasterProtein OR IsMasterProteinCandidate) AND Protein FDR Confidence == HIGH
filterMS <- function(ms_data){
  select <- (ms_data[,grepl("Master", colnames(ms_data))] == "IsMasterProtein") &
             ms_data[,grepl("FDR", colnames(ms_data))] == "High"
  
  return(ms_data[select,])
}

doGO <- function(DEPlist, universeList, sample){
  # Do GO
  ontologyTab <- tibble()
  ontologies <- c("BP","CC", "MF")
  for (o in 1:3){
      goTab<- enrichGO(gene = as.character(DEPlist),
                  universe = as.character(universeList),
                  OrgDb = org.Hs.eg.db,
                  ont = ontologies[o],
                  pAdjustMethod = "BH",
                  pvalueCutoff = 0.05,
                  qvalueCutoff = 0.1,
                  readable = T,
                  minGSSize = 5)
      
        goTab <- as.data.frame(goTab) %>%
          separate(GeneRatio, c("n", "N"), "/", remove = F) %>%
          separate(BgRatio, c("b", "B"), "/", remove = F) %>%
          mutate(n = as.numeric(n),
                 N = as.numeric(N),
                 b = as.numeric(b),
                 B = as.numeric(B),
                 EnrichmentScore = (n/N)/(b/B))  %>%
          #filter(n > 10,
          #       b > 20)  %>% 
          arrange(desc(EnrichmentScore)) %>%
          mutate(group = paste("GO", ontologies[o]),
                 sample = sample) 
            
        toSave <- goTab
        
        if(nrow(ontologyTab) == 0){
          ontologyTab <- toSave
        } else {
          ontologyTab <- ontologyTab %>%
            full_join(toSave)
        }      
  }
  
  return(ontologyTab)
}
```

```{r}
#Load metadata
metadata <- read_csv("data/metadata.csv")  

#Load MS data
U2932_DX_KD_data <- read_csv("data/U2932-DDX3X-KD_MS_data.csv")
colnames(U2932_DX_KD_data) <- sub("Abundances [(]Grouped[)]: ", 
                                         "Abundances..Grouped...", 
                                         colnames(U2932_DX_KD_data))

U2932_clones_DY_KD_data <- read_csv("data/U2932-clones-DY-KD_MS_data.csv") %>%
  mutate(Name = splitvec(splitvec(Description, "GN=", 2), " ", 1)) 
U2932_clones_DY_KD_data <- U2932_clones_DY_KD_data[,c(31,1:30)]
colnames(U2932_clones_DY_KD_data) <- sub("Abundances [(]Grouped[)]: ", 
                                         "Abundances..Grouped...", 
                                         colnames(U2932_clones_DY_KD_data))

#Filter MS data
U2932_DX_KD_data <- filterMS(U2932_DX_KD_data)
dim(U2932_DX_KD_data)
U2932_clones_DY_KD_data <- filterMS(U2932_clones_DY_KD_data)
dim(U2932_clones_DY_KD_data)
```

### Exploratory plots  

### Boxplots: evaluate need for normalization  

```{r, warning=FALSE, message=FALSE, echo = TRUE, fig.width=10, fig.height=4}
#U2932_DX_KD
select <- grep("Abundances", colnames(U2932_DX_KD_data))
boxplot(log2(U2932_DX_KD_data[,select]), 
        names = metadata$condition[metadata$experiment == "U2932_DX"], las = 2,
        col = divergingPal[as.factor(metadata$condition[metadata$experiment == "U2932_DX"])])
abline(h=median(as.matrix(log2(U2932_DX_KD_data[,select[-1:-8]])), na.rm = T))

#U2932_clones_DY_KD
select <- grep("Abundances", colnames(U2932_clones_DY_KD_data))[c(-1:-4)]
boxplot(log2(U2932_clones_DY_KD_data[,select]), 
        names = metadata$condition[metadata$experiment == "U2932_cl"], las = 2,
        col = divergingPal[as.factor(metadata$condition[metadata$experiment == "U2932_cl"])])
abline(h=median(as.matrix(log2(U2932_clones_DY_KD_data[,select[-1:-8]])), na.rm = T))
```

### Histograms  

```{r, warning=FALSE, message=FALSE, echo = TRUE, fig.width=10, fig.height=4}
#U2932_DX_KD
select <- grep("Abundances", colnames(U2932_DX_KD_data))
plot_df <- log2(U2932_DX_KD_data[,select]) %>% gather()
match <- match(plot_df$key, metadata$label[metadata$experiment == "U2932_DX"])
plot_df$condition <- metadata$condition[metadata$experiment == "U2932_DX"][match]

ggplot(plot_df) + 
  geom_freqpoly(aes(x = value, color = condition, group = key), size = 1, alpha = 0.7) +
  nature_point() +
  scale_color_manual(values = divergingPal[-1:-8])

#U2932_clones_DY_KD
select <- grep("Abundances", colnames(U2932_clones_DY_KD_data))
plot_df <- log2(U2932_clones_DY_KD_data[,select]) %>% gather()
match <- match(plot_df$key, metadata$label[metadata$experiment == "U2932_cl"])
plot_df$condition <- metadata$condition[metadata$experiment == "U2932_cl"][match]

ggplot(plot_df) + 
  geom_freqpoly(aes(x = value, color = condition, group = key), size = 1, alpha = 0.7) +
  nature_point() +
  scale_color_manual(values = divergingPal)

```

### Test MS data, save the results  

#### U2932 DDX3X knock-down  

```{r, warning=FALSE, message=FALSE, echo = TRUE}
U2932_DX_KD_results <- DEPtest(ms_data = U2932_DX_KD_data, 
                               metadata = metadata, 
                               Experiment = "U2932_DX", 
                               Conditions = c("ctl", "sh"), 
                               padj = 0.1, lfc = log2(1.25), 
                               normalize = T)

write.csv(U2932_DX_KD_results[[1]], "results/DEP_U2932_DX_KD_all.csv", row.names = F)
tab <- U2932_DX_KD_results[[1]]
#Plots
hist(U2932_DX_KD_results[[1]]$P_value)
plot_pca(U2932_DX_KD_results[[2]], x = 1, y = 2, n = 500, point_size = 4) # PCA
plot_cor(U2932_DX_KD_results[[2]], significant = TRUE, lower = 0.8, upper = 1, pal = "Blues") # Correlation
plot_volcano(U2932_DX_KD_results[[2]], contrast = "sh_vs_ctl", label_size = 2, add_names = TRUE) #Volcano

#VST
U2932_DX_KD_vst <- as.tibble(assay(U2932_DX_KD_results[[3]])) 
U2932_DX_KD_vst$Name <- rownames(U2932_DX_KD_results[[3]])
write_csv(U2932_DX_KD_vst, "results/VST_U2932_DDX3Xkd.csv")
```

#### U2932 DDX3X mut vs. wt

```{r, warning=FALSE, message=FALSE, echo = TRUE}
#U2932_clones
U2932_clones_DY_KD_data
U2932_clones_results <- DEPtest(ms_data = U2932_clones_DY_KD_data, 
                                metadata = metadata, 
                                Experiment = "U2932_cl", 
                                Conditions = c("U2932_WT", "U2932_MUT"), 
                                padj = 0.1, 
                                lfc = log2(1.25), 
                                normalize = F)

write.csv(U2932_clones_results[[1]], "results/DEP_U2932_clones_all.csv", row.names = F)

# Plots 
hist(U2932_clones_results[[1]]$P_value)
plot_pca(U2932_clones_results[[2]], x = 1, y = 2, n = 500, point_size = 4) # PCA
plot_cor(U2932_clones_results[[2]], significant = TRUE, lower = 0.8, upper = 1, pal = "Blues") # Correlation
plot_volcano(U2932_clones_results[[2]], contrast = "U2932_MUT_vs_U2932_WT", label_size = 2, add_names = TRUE) #Volcano

#VST
U2932_clones_vst <- as.tibble(assay(U2932_clones_results[[3]]), ) 
U2932_clones_vst$Name <- rownames(U2932_clones_results[[3]])
```

### Gene ontology analysis  

```{r}
U2932_clonesTab <- U2932_clones_results[[1]] %>%
  mutate(ID = splitvec(ID, "-", 1))

U2932_kdTab <- U2932_DX_KD_results[[1]]%>%
  mutate(ID = splitvec(ID, "-", 1))
```

```{r}
# Download annotations
ens <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
entrezIDs <- getBM(attributes=c('entrezgene_id', 
                                'external_gene_name',
                                'gene_biotype',
                                'uniprot_gn_id'), 
                   filters = "uniprot_gn_id",
                   values = unique(c(U2932_clonesTab$ID, U2932_clonesTab$ID)), 
                   mart = ens) %>%
  na.omit()

# Integrate
U2932_clonesTab <- U2932_clonesTab %>% 
  left_join(entrezIDs, by = c("ID" = "uniprot_gn_id")) %>%
  na.omit()
U2932_kdTab <- U2932_kdTab %>%
  left_join(entrezIDs, by = c("ID" = "uniprot_gn_id")) %>%
  na.omit()

# Generate clean tables  
## U2932 clones
U2932_clonesTabSuppl <- U2932_clones_results[[1]] %>%
  mutate(ID = splitvec(ID, "-", 1)) %>% 
  left_join(entrezIDs, by = c("ID" = "uniprot_gn_id")) %>% 
  left_join(U2932_clones_vst) 

U2932_clonesTabSuppl <- U2932_clonesTabSuppl %>%
  mutate(Signif = FDR < 0.1,
         Status = case_when(
           FDR < 0.1 & log2FC < 0 ~ "Down",
           FDR < 0.1 & log2FC > 0 ~ "Up",
           TRUE ~ "Stable"
         )) %>%
  dplyr::select(Name, ID,entrezgene_id, P_value, FDR, log2FC, Signif, Status, starts_with("U2932")) %>%
  arrange(FDR)

write_csv(U2932_clonesTabSuppl, "results/U2932_clones_sumtab.csv")

## U2932 DDX3X kd 
U2932_kdTabSuppl <- U2932_DX_KD_results[[1]]%>%
  mutate(ID = splitvec(ID, "-", 1)) %>% 
  left_join(entrezIDs, by = c("ID" = "uniprot_gn_id")) %>% 
  left_join(U2932_DX_KD_vst) 

U2932_kdTabSuppl <- U2932_kdTabSuppl %>%
  mutate(Signif = FDR < 0.1,
         Status = case_when(
           FDR < 0.1 & log2FC < 0 ~ "Down",
           FDR < 0.1 & log2FC > 0 ~ "Up",
           TRUE ~ "Stable"
         )) %>%
  dplyr::select(Name, ID,entrezgene_id, P_value, FDR, log2FC, Signif, Status, 
                starts_with("ctl"),starts_with("sh")) %>%
  arrange(FDR)

write_csv(U2932_kdTabSuppl, "results/U2932_DXsh_sumtab.csv")
```

#### Gene ontology analysis  

```{r}
universeList <- read_csv("../09_U2932clones/tables/U2932clones_RNA_sumtab.csv")$entrezgene_id

# U2932 DDX3X knock-down
DEPlist <- U2932_kdTab$entrezgene_id[U2932_kdTab$FDR < 0.1 & U2932_kdTab$log2FC < 0]
GO_DXkd_down <- doGO(DEPlist, universeList, "Down") 

DEPlist <- U2932_kdTab$entrezgene_id[U2932_kdTab$FDR < 0.1 & U2932_kdTab$log2FC > 0]
GO_DXkd_up <- doGO(DEPlist, universeList, "Up") 

GO_DXkd_all <- GO_DXkd_down %>%
  full_join(GO_DXkd_up) %>%
  filter( n > 5)

# U2932 DDX3X knock-dow
DEPlist <- U2932_clonesTab$entrezgene_id[U2932_clonesTab$FDR < 0.1 & U2932_clonesTab$log2FC < 0]
GO_DXclones_down <- doGO(DEPlist, universeList, "Down") 

DEPlist <- U2932_clonesTab$entrezgene_id[U2932_clonesTab$FDR < 0.1 & U2932_clonesTab$log2FC > 0]
GO_DXclones_up <- doGO(DEPlist, universeList, "Up") 

GO_DXclones_all <- GO_DXclones_down %>%
  full_join(GO_DXclones_up) %>%
  filter( n > 6)

# Pathways analysis
m_t2g_pathways <- msigdbr(species = "Homo sapiens", category = "C5") %>% 
  dplyr::select(gs_name, entrez_gene)

geneList <- U2932_kdTab$entrezgene_id[U2932_kdTab$FDR < 0.1 & U2932_kdTab$log2FC < 0]
MS_DXsh_paths <- enricher(as.character(geneList), TERM2GENE=m_t2g_pathways, 
                          universe = as.character(universeList), pvalueCutoff = 0.1) %>%
  as.data.frame()
```

```{r, fig.height=4, fig.width=2}
# Visualise
# DDX3X kd
plot_df <- GO_DXkd_all %>%
  group_by(group, sample) %>%
  mutate(rank = rank(-EnrichmentScore)) 

#write_csv(plot_df, "results/MS_DXsh_U2932_GOplotDf.csv")

plot_df <- plot_df %>%
  filter(rank < 5) %>%
  ungroup() %>%
  arrange(group, p.adjust) %>%
  mutate(Description = factor(Description, levels = Description[order(p.adjust, decreasing = T)]),
         rank = factor(as.character(1:length(Description)), 
                       levels = as.character(1:length(Description))))

pF <- plot_df %>%
  filter(sample == "Down")
ggplot(pF, aes(x = Description, y = -log10(p.adjust))) +
  geom_bar(aes(fill = rank), stat = "identity") +
  geom_text(aes(label = paste(n, b, sep = "/")), 
            position = position_identity(), hjust = 1.2, 
            colour = "white") +
  facet_grid(group+sample ~., scales = "free", space = "free") +
  coord_flip() +
  nature_barplot() +
  labs(y =  bquote(~-Log[10]~'(FDR)'), x = "", colour = "", title = "U2932") +
  theme(legend.position = "None") +
  scale_fill_manual(values = colorRampPalette(brewer.pal(11, "Spectral")[c(1,2,3,4,5,9,10,11,12)])(14)) +
  theme(strip.text.y = element_text(margin = margin(2,2,2,2)))

ggsave("plots/U2932_DDX3Xkd_MSdown_GO.pdf", width = 13, height = 6, useDingbats = F)

pF <- plot_df %>%
  filter(sample == "Up")

ggplot(pF, aes(x = Description, y = -log10(p.adjust))) +
  geom_bar(aes(fill = rank), stat = "identity") +
  geom_text(aes(label = paste(n, b, sep = "/")), 
            position = position_identity(), hjust = 1.2, 
            colour = "white") +
  facet_grid(group+sample ~., scales = "free", space = "free") +
  coord_flip() +
  nature_barplot() +
  labs(y =  bquote(~-Log[10]~'(FDR)'), x = "", colour = "", title = "U2932") +
  theme(legend.position = "None") +
  scale_fill_manual(values = colorRampPalette(brewer.pal(11, "Spectral")[c(1,2,3,4,5,9,10,11,12)])(14)) +
  theme(strip.text.y = element_text(margin = margin(2,2,2,2)))

ggsave("plots/U2932_DDX3Xkd_MSup_GO.pdf", width = 13, height = 2, useDingbats = F)

# Heatmap
U2932_DX_KD_vst <- U2932_DX_KD_vst %>%
  mutate(log2FC_1 = sh_1-ctl_1,
         log2FC_2 = sh_2-ctl_2)

RPs_cytosolic <- RPs %>%
  filter(!grepl("mitochondrial", Class))

plot_df <- U2932_DX_KD_vst %>%
  filter(Name %in% RPs_cytosolic$Approved_symbol) %>% 
  dplyr::select(Name, ctl_1,ctl_2,sh_1,sh_2) %>%
  mutate(Name = splitvec(Name, "[.]", 1)) %>%
  group_by(Name) %>%
  summarize(ctl_1 = mean(ctl_1),
         ctl_2 = mean(ctl_2),
         sh_1 = mean(sh_1),
         sh_2 = mean(sh_2)) %>%
  column_to_rownames("Name") 

# Annotations
annotation_col <- data.frame(Condition = c("ctl", "ctl", "sh", "sh"))
rownames(annotation_col) <- colnames(plot_df)
Var1 = c(divergingPal[c(10)], brewer.pal(11,"RdYlGn")[10])
names(Var1) = unique(annotation_col$Condition) 

ann_colors = list(Condition = Var1) 

palette <- rev(colorRampPalette(c(divergingPal[2], "white", divergingPal[10]))(100))
set.seed(3)
pheatmap(plot_df, 
         scale = "row",
         cluster_cols = F, 
         cluster_rows = T,
         clustering_distance_rows = "euclidean",
         clustering_method = "complete",
         color = palette, 
         cellwidth = 20,
         cellheight = 10, 
         fontsize_row = 10,
         annotation_col = annotation_col, 
         annotation_colors = ann_colors,
         filename = paste0("plots/Heatmap_DDX3Xsh_u2932.pdf")
         )

#
changed <- U2932_clonesTab$Name[U2932_clonesTab$FDR < 0.1]
U2932_clones_vst <- U2932_clones_vst 
mSigC5 <- msigdbr(species = "Homo sapiens", category = "C5")
path1 <- mSigC5 %>% 
  filter(gs_name == "GO_ENDOPLASMIC_RETICULUM")
path2 <- mSigC5 %>% 
  filter(gs_name == "GO_ERAD_PATHWAY")

plot_df <- U2932_clones_vst %>%
  filter(Name %in% changed) %>% 
  dplyr::select(Name, starts_with("U2932")) %>%
  group_by(Name) %>%
  summarize(U2932_WT_1 = mean(U2932_WT_1),
            U2932_WT_2 = mean(U2932_WT_2),
            U2932_WT_3 = mean(U2932_WT_3),
            U2932_MUT_1 = mean(U2932_MUT_1),
            U2932_MUT_2 = mean(U2932_MUT_2),
            U2932_MUT_3 = mean(U2932_MUT_3)) %>%
  column_to_rownames("Name") 

plot_df <- t(plot_df)

# Annotations
annotation_col <- data.frame(ER = as.character(colnames(plot_df) %in% path1$human_gene_symbol),
                             UPR = as.character(colnames(plot_df) %in% path2$human_gene_symbol))

row.names(annotation_col) <- colnames(plot_df)
Var1 = divergingPal[c(12,2)]
names(Var1) = unique(annotation_col$ER) 
Var2 = divergingPal[c(12,3)]
names(Var2) = unique(annotation_col$UPR) 

ann_colors = list(ER = Var1,
                  UPR = Var2) 

palette <- rev(colorRampPalette(c(divergingPal[2], "white", divergingPal[10]))(100))
set.seed(3)

order_tab <- annotation_col %>%
  rownames_to_column("Name") %>%
  mutate(Lp = 1: nrow(annotation_col),
         HitsSum = as.numeric(as.logical(ER)) + as.numeric(as.logical(UPR))) %>%
  left_join(U2932_clonesTabSuppl, by = "Name") %>%
  arrange(Status, HitsSum)%>%
  distinct()
  
plot_df2 <- plot_df[,unique(order_tab$Lp)]

pheatmap(plot_df2, 
         scale = "column",
         cluster_cols = F, 
         cluster_rows = F,
         clustering_distance_rows = "euclidean",
         clustering_method = "complete",
         color = palette, 
         show_colnames = F,
         cellwidth = 1,
         cellheight = 10, 
         fontsize_row = 10,
         annotation_col = annotation_col, 
         annotation_colors = ann_colors, 
         filename = "plots/Heatmap_U2932clones.pdf")
```

```{r}
# Visualise
# DDX3X clones
plot_df <- GO_DXclones_all %>%
  group_by(group, sample) %>%
  mutate(rank = rank(-EnrichmentScore)) 

write_csv(plot_df, "results/MS_DXclones_U2932_GOplotDf.csv")

plot_df <- plot_df %>%
  filter(rank < 5) %>%
  ungroup() %>%
  arrange(group, p.adjust) %>%
  mutate(Description = factor(Description, levels = Description[order(p.adjust, decreasing = T)]),
         rank = factor(as.character(1:length(Description)), 
                       levels = as.character(1:length(Description))))

ggplot(plot_df, aes(x = Description, y = -log10(p.adjust))) +
  geom_bar(aes(fill = rank), stat = "identity") +
  geom_text(aes(label = paste(n, b, sep = "/")), 
            position = position_identity(), hjust = 1.2, 
            colour = "white") +
  facet_grid(group ~., scales = "free", space = "free") +
  coord_flip() +
  nature_barplot() +
  labs(y =  bquote(~-Log[10]~'(FDR)'), x = "", colour = "", title = "U2932") +
  theme(legend.position = "None") +
  scale_fill_manual(values = colorRampPalette(brewer.pal(11, "Spectral")[c(1,2,3,4,5,9,10,11,12)])(12)) +
  theme(strip.text.y = element_text(margin = margin(2,2,2,2)))

ggsave("plots/U2932_DDX3Xclones_MSdown_GO.pdf", width = 13, height = 6, useDingbats = F)
```

```{r eval = T, echo = T, message = F, warning = F, error = F}  
sessionInfo()
```